### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by MihaiAnei** [pinojs/koa-pino-logger#25]
Given that is really useful for Koa apps and logging aggregation. I am asking because I am seeing the open pull requests and issues without activity in a long time.

**Comment by katlimruiz** [comment]
+1

**Comment by yorch** [comment]
@davidmarkclements, thanks for your work on this open source project, it's great help!

I was gonna put a PR to update to latest `pino-http` since I'm missing some features, but found out that there are PRs from other people already that haven't been merged and no feedback whatsoever. Is this project still gonna be maintained or should we look for a replacement?

Thanks!

**Comment by yorch** [comment]
@mcollina any thoughts? ^
