### ISSUE TITLE
Expose or Document Exposure of pino-http opts.logger

### ISSUE THREAD

**Issue by eudaimos** [pinojs/koa-pino-logger#5]
In my Koa v2 app I instantiate a pino logger to log what the server is doing on init and shutdown.

`pino-http` exposes an option to reuse an already instantiated `pino` logger by passing the `logger` option (see [here](https://github.com/pinojs/pino-http#pinohttpopts-stream)).

I've tried `koa-pino-logger` by passing the `logger` option in and it _"seems"_ to work but I can't tell if it's creating a new one or not.  Either way, I would like to reuse my `pino` logger in this way, so can you please either expose the `pino-http` `logger` option or if it already works, then document it in the API docs?

_Happy to submit a PR with updated docs if that's what you'd prefer_

**Comment by davidmarkclements** [comment]
`opts` get's passed through to [`pino-http`](http://npm.im/pino-http)

`pino-http` looks for `logger` on `opts` and actually spawns a child from it
(because the opts that `pino-http` sets, in particular for serializer request is different)
(see https://github.com/pinojs/pino-http/blob/master/logger.js#L83-L99)

So either way, you're basically getting a new instance, except by passing in 
a pino instance to opts.logger you're reusing the same proto methods and small
amount of shared state - plus ensuring that the pino version is consistent
